version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - apt-get update -y
      - apt install --reinstall sed
      - git config --global url."https://$GITHUB_TOKEN:x-oauth-basic@github.com/".insteadOf "https://github.com/"
  post_build:
    commands:
      - sed -i -e "s/{PARAM_PREFIX}/$PREFIX/g; s/{PARAM_ENVIRONMENT}/$ENVIRONMENT/g; s/{PARAM_BUCKETNAME}/$S3BUCKETNAME/g" configuration.json
      - aws cloudformation package --template-file s3_SNS_IAM.yml --s3-bucket $ARTIFACTS_BUCKET --output-template-file s3_SNS_IAM_release.yml
      - aws s3 cp configuration.json s3://$ARTIFACTS_BUCKET/confmakeiguration.json
      - cd -
      - ls -la
artifacts:
  files:
    - 's3_SNS_IAM_release.yml'
    - 'configuration.json'
  discard-paths: yes