# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      Access_Key: ${{secrets.ACCESS_KEY}}
      Secret_Key: ${{secrets.SECRET_KEY}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: sed -i -e "s|{Secret_Key}|${{env.Secret_Key}}|g; s|{Access_Key}|${{env.Access_Key}}|g" .github/workflows/scripts/cfn.json
      - run: cat .github/workflows/scripts/cfn.json
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: change file permissions
        run: chmod 777 .github/workflows/scripts/gw_deploy.sh

      - name: starting thr deployment process
        run: .github/workflows/scripts/gw_deploy.sh
